version: '3'
services:
  frontend:
    build:
      dockerfile: Dockerfile
      context: ./frontend
    container_name: medium-docker-frontend
    command: serve -s dist/medium -l 3001
    restart: unless-stopped
    stdin_open: true
    tty: true
    volumes:
      - ./frontend/src:/usr/src/app/src
    networks:
      - medium-docker-network

  api:
    build: ./api
    container_name: medium-docker-api
    command: npm run start
    restart: unless-stopped
    environment:
      - PORT=3000
      - DATABASE_URL=postgres://api_db:5432/medium_db
    depends_on:
      - api_db
    networks:
      - medium-docker-network

  api_db:
    image: postgres:15.2-alpine
    container_name: medium_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: medium_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: root
    volumes:
      - postgresdb_api:/var/lib/postgresql/data
    networks:
      - medium-docker-network

  nginx:
    image: nginx:stable-alpine
    container_name: medium-docker-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf.prod:/etc/nginx/conf.d/nginx.conf
    depends_on:
      - frontend
      - api
    networks:
      - medium-docker-network

volumes:
  postgresdb_api:

networks:
  medium-docker-network:
    driver: bridge